### ISSUE TITLE
ViaProxy 1.8 client cannot join 1.20.4 spigot/vanilla/LAN server

### ISSUE THREAD

**Issue by ayunami2000** [ViaVersion/ViaProxy#182]
![image](https://github.com/ViaVersion/ViaProxy/assets/24785136/fbccd925-c144-4b20-8981-5a2ae4e6bb26)
Tested with these plugins on a spigot 1.20.4 server instead of ViaProxy, it functions as expected from a 1.8 client.

Error logs:
```
[15:48:29] [Netty NIO Client IO #4/WARN] (ViaVersion) ERROR IN Protocol1_20To1_20_2 IN REMAP OF CONFIGURATION 0x08->0xFFFFFFFF
[15:48:29] [Netty NIO Client IO #4/ERROR] (ViaProxy) Caught unhandled netty exception
 io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: VarInt, Index: 3, Data: [{VarInt: 1}, {StringType: minecraft:vanilla}], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$1244/1997753864, Packet ID: -1
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at net.raphimc.vialoader.netty.ViaCodec.channelRead(ViaCodec.java:81) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at net.raphimc.viaproxy.protocoltranslator.impl.ViaProxyViaCodec.channelRead(ViaProxyViaCodec.java:41) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_391]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: VarInt, Index: 3, Data: [{VarInt: 1}, {StringType: minecraft:vanilla}], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$1244/1997753864, Packet ID: -1
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(20) + length(1) exceeds writerIndex(20): PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:142) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.rewriter.TagRewriter.handle(TagRewriter.java:199) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.rewriter.TagRewriter.lambda$getGenericHandler$2(TagRewriter.java:188) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.lambda$registerPackets$11(Protocol1_20To1_20_2.java:155) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:427) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.transform(Protocol1_20To1_20_2.java:173) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at net.raphimc.vialoader.netty.ViaCodec.decode(ViaCodec.java:57) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[ViaProxy-3.2.0-SNAPSHOT+java8.jar:?]
        ... 42 more
[15:48:29] [Netty NIO Client IO #4/ERROR] (ViaProxy) [PROXY KICK] (127.0.0.1:9871 | ayunami2000) An unhandled error occurred in your connection and it has been closed.
Error details for report:
InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: VarInt, Index: 3, Data: [{VarInt: 1}, {StringType: minecraft:vanilla}], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$1244/1997753864, Packet ID: -1 Caused by
IndexOutOfBoundsException: readerIndex(20) + length(1) exceeds writerIndex(20): PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 256)
```
![image](https://github.com/ViaVersion/ViaProxy/assets/24785136/55de2d75-a887-4b75-8bdc-1ac90c882945)

**Comment by RaphiMC** [comment]
Fixed in the latest dev build: https://ci.viaversion.com/view/Platforms/job/ViaProxy/
