### ISSUE TITLE
client 24w07a connecting to server on earlier version not working on some servers

### ISSUE THREAD

**Issue by ojoghjffo** [ViaVersion/ViaProxy#189]
![2024-02-25_01 32 55](https://github.com/ViaVersion/ViaProxy/assets/94257288/dba98f19-6e1a-4caf-9d7c-da11b68ba3dc)

This happens when I try to join play.datblock.com on 24w07a using ViaProxy 3.2.0

Joining that server works fine with 23w51b on ViaProxy 3.1.0

[01:17:08] [main/INFO] (ViaProxy) Initializing ViaProxy GUI v3.2.0 (git-ViaProxy-3.2.0:71ff0cc) (Injected using Launcher Agent)...
[01:17:08] [main/INFO] (ViaProxy) Using java version: OpenJDK 64-Bit Server VM 17.0.1 (Microsoft) on Windows 10
[01:17:08] [main/INFO] (ViaProxy) Available memory (bytes): 1025507328
[01:17:08] [main/INFO] (ViaProxy) Working directory: C:\Users\********\Desktop\Artifacts (3)
[01:17:11] [main/INFO] (ViaBackwards) Loading translations...
[01:17:11] [Via-Mappingloader-0/INFO] (ViaVersion) Loading block connection mappings ...
[01:17:12] [main/INFO] (ViaBackwards) Registering protocols...
[01:17:17] [main/INFO] (ViaBedrock) Started resource pack HTTP server on http://127.0.0.1:53601/
[01:17:18] [main/INFO] (ViaVersion) ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[01:17:18] [main/INFO] (ViaVersion) Highest supported version by the proxy: 24w07a (766)
[01:17:26] [main/INFO] (ViaProxy) ViaProxy started successfully!
[01:18:00] [Via Async Scheduler 0/INFO] (ViaVersion) Finished mapping loading, shutting down loader executor!
[01:18:17] [Thread-3/INFO] (ViaProxy) Starting proxy server
[01:18:17] [Thread-3/INFO] (ViaProxy) Binding proxy server to 0.0.0.0:25568
[01:18:22] [Netty NIO Server Child IO #0/INFO] (ViaProxy) [CONNECT] (127.0.0.1:53604 | null) [24w07a <-> 1.20.3-1.20.4] Connecting to play.datblock.com.:25565
[01:18:24] [Netty NIO Client IO #0/INFO] (ViaProxy) [DISCONNECT] (127.0.0.1:53604 | null) Connection closed
[01:18:26] [Netty NIO Server Child IO #1/INFO] (ViaProxy) [CONNECT] (127.0.0.1:53607 | null) [24w07a <-> 1.20.3-1.20.4] Connecting to play.datblock.com.:25565
[01:18:26] [Netty NIO Server Child IO #1/INFO] (ViaProxy) [AUTH] (127.0.0.1:53607 | Plmqazoknedc) Filling player data
[01:18:26] [Netty NIO Server Child IO #1/INFO] (MinecraftAuth) Getting profile...
[01:18:27] [Netty NIO Server Child IO #1/INFO] (MinecraftAuth) Got MC Profile, name: Plmqazoknedc, uuid: 5eecf5c3-406a-4986-9fff-74cbc93e60fd
[01:18:28] [Netty NIO Client IO #1/INFO] (ViaProxy) [AUTH] (127.0.0.1:53607 | Plmqazoknedc) Trying to join online mode server
[01:18:28] [Netty NIO Client IO #1/INFO] (YggdrasilAuthenticationService) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:18:28] [Netty NIO Client IO #1/INFO] (ViaProxy) [AUTH] (127.0.0.1:53607 | Plmqazoknedc) Requesting nonce signature
[01:18:29] [Netty NIO Client IO #1/INFO] (ViaProxy) [SESSION] (127.0.0.1:53607 | Plmqazoknedc) Connected successfully! Switching to CONFIGURATION state
[01:18:32] [Netty NIO Client IO #1/INFO] (ViaProxy) [SESSION] (127.0.0.1:53607 | Plmqazoknedc) Configuration finished! Switching to PLAY state
[01:18:33] [Netty NIO Client IO #1/ERROR] (ViaProxy) Caught unhandled netty exception
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1/1)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[ViaProxy-3.2.0.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[ViaProxy-3.2.0.jar:?]
	at net.raphimc.netminecraft.packet.PacketTypes.readVarInt(PacketTypes.java:52) ~[ViaProxy-3.2.0.jar:?]
	at net.raphimc.netminecraft.packet.impl.configuration.S2CConfigTransfer1_20_5.read(S2CConfigTransfer1_20_5.java:40) ~[ViaProxy-3.2.0.jar:?]
	at net.raphimc.viaproxy.proxy.packethandler.TransferPacketHandler.handleP2S(TransferPacketHandler.java:50) ~[ViaProxy-3.2.0.jar:?]
	at net.raphimc.viaproxy.proxy.proxy2server.Proxy2ServerHandler.channelRead0(Proxy2ServerHandler.java:60) ~[ViaProxy-3.2.0.jar:?]
	at net.raphimc.viaproxy.proxy.proxy2server.Proxy2ServerHandler.channelRead0(Proxy2ServerHandler.java:32) ~[ViaProxy-3.2.0.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0.jar:?]
	at net.raphimc.vialoader.netty.ViaCodec.channelRead(ViaCodec.java:81) [ViaProxy-3.2.0.jar:?]
	at net.raphimc.viaproxy.protocoltranslator.impl.ViaProxyViaCodec.channelRead(ViaProxyViaCodec.java:41) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.2.0.jar:?]
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [ViaProxy-3.2.0.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [ViaProxy-3.2.0.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [ViaProxy-3.2.0.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [ViaProxy-3.2.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
[01:18:33] [Netty NIO Client IO #1/ERROR] (ViaProxy) [PROXY KICK] (127.0.0.1:53607 | Plmqazoknedc) [0m[38;2;255;85;85mAn unhandled error occurred in your connection and it has been closed.
[0m[38;2;85;255;85mError details for report:[0m[38;2;255;255;255m
[0m[38;2;255;85;85mIndexOutOfBoundsException[0m[38;2;170;170;170m: [0m[38;2;255;255;255mreaderIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1/1)[0m
[01:18:33] [Netty NIO Client IO #1/INFO] (ViaProxy) [DISCONNECT] (127.0.0.1:53607 | Plmqazoknedc) Connection closed

**Comment by RaphiMC** [comment]
Fixed in latest ViaProxy dev build: https://ci.viaversion.com/view/Platforms/job/ViaProxy/
