### ISSUE TITLE
error IllegalStateException: Unexpected packet in HANDSHAKING state

### ISSUE THREAD

**Issue by X1nDi** [ViaVersion/ViaProxy#240]
[13:02:20] [Geyser Scheduled Thread-3-1/WARN] (Geyser) Failed to ping the remote Java server! Is it online and configured in Geyser's config?
[13:02:20] [Via Async Scheduler 0/INFO] (ViaVersion) Finished mapping loading, shutting down loader executor!
[13:02:23] [Netty Epoll Server Child IO #1/ERROR] (ViaProxy) Caught unhandled netty exception
 java.lang.IllegalStateException: Unexpected packet in HANDSHAKING state
        at net.raphimc.viaproxy.proxy.client2proxy.Client2ProxyHandler.channelRead0(Client2ProxyHandler.java:95) ~[ViaProxy-3.3.1.jar:?]
        at net.raphimc.viaproxy.proxy.client2proxy.Client2ProxyHandler.channelRead0(Client2ProxyHandler.java:66) ~[ViaProxy-3.3.1.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [ViaProxy-3.3.1.jar:?]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) [ViaProxy-3.3.1.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) [ViaProxy-3.3.1.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) [ViaProxy-3.3.1.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [ViaProxy-3.3.1.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[13:02:23] [Netty Epoll Server Child IO #1/INFO] (ViaProxy) [PROXY KICK] (127.0.0.1:51130 | null) An unhandled error occurred in your connection and it has been closed.
Error details for report:
IllegalStateException: Unexpected packet in HANDSHAKING state
[13:02:23] [Geyser Scheduled Thread-3-1/WARN] (Geyser) Failed to ping the remote Java server! Is it online and configured in Geyser's config?

**Comment by RaphiMC** [comment]
Please provide more details, such as ViaProxy configuration, full log and Geyser configuration

**Comment by X1nDi** [comment]
[3.zip](https://github.com/user-attachments/files/16227554/3.zip)
and I using tcp-shield
![image](https://github.com/user-attachments/assets/5e0078e7-20c9-4f86-a267-23afc57f1d36)

**Comment by RaphiMC** [comment]
You need to enable `frontend-haproxy` in the ViaProxy config (Or disable proxy protocol in TCPShield)

**Comment by X1nDi** [comment]
if remote adress in config geyser is localhost:
[16:51:41] [tcpClientSession-7-1/INFO] (Geyser) flotreke has disconnected from remote Java server on address 127.0.0.1 because of Не удалось подключиться к серверу Java Edition! Этот сервер или не запущен, или не принимает подключения.
[16:51:41] [tcpClientSession-7-1/ERROR] (Geyser) finishConnect(..) failed: Connection refused: /127.0.0.1:25565


if remote adress in config geyser is:
![image](https://github.com/user-attachments/assets/9d734250-71fa-45c3-ae39-7dabe80e233d)

**Comment by RaphiMC** [comment]
You configured ViaProxy to connect to 127.0.0.1:25565 and apparently there is no server running there (Or your misconfigured the server or ViaProxy)

**Comment by X1nDi** [comment]
yes, but if i set auto in remote adress:
https://private-user-images.githubusercontent.com/80688187/348547590-9d734250-71fa-45c3-ae39-7dabe80e233d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjU1ODUsIm5iZiI6MTcyMDk2NTI4NSwicGF0aCI6Ii84MDY4ODE4Ny8zNDg1NDc1OTAtOWQ3MzQyNTAtNzFmYS00NWMzLWFlMzktN2RhYmU4MGUyMzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDEzNTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMTgwZDcyNzc3OWZlYzZiNzlkODc0YmUwZGI5YjU2NDYwN2YyM2Y5Mjk2NGJiMjA3MTRhNzQ1MzQzY2UxNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SK_eySg_GYIt0JDEcR8RdrObKqw0iUYOavg7NZrLxMw

**Comment by RaphiMC** [comment]
As I said, you have no server running on 127.0.0.1:25565 or you misconfigured it. Maybe the server expectes proxy protocol to be enabled. In that case enable `backend-haproxy` in the ViaProxy config or disable it on the backend server

**Comment by X1nDi** [comment]
Why this error? 
[17:13:44] [epollEventLoopGroup-5-2/INFO] (Geyser) Bedrock user with ip: /2.63.1.137 has disconnected for reason Outdate|
d Bedrock client! This server supports the following Bedrock versions: 1.20.80/1.20.81, 1.21.0/1.21.1, 1.21.2

**Comment by RaphiMC** [comment]
Your bedrock client is too old for Geyser

**Comment by X1nDi** [comment]
а зачем тогда нужен via proxy? я думал via proxy это как via version, чтобы зайти можно было со старых версий

**Comment by X1nDi** [comment]
how do I make it possible for my server to be accessed from older versions of bedrock

**Comment by RaphiMC** [comment]
> then why do I need a via proxy? I thought via proxy was like via version, so that you could log in from older versions

ViaProxy is for java edition client/servers. It only supports latest bedrock through Geyser



> how do I make it possible for my server to be accessed from older versions of bedrock

Not possible to my knowledge

**Comment by X1nDi** [comment]
and if I install the geyser of the old version, will it be possible to log in to the server with the new version of bedrock?

**Comment by RaphiMC** [comment]
> and if I install the geyser of the old version, will it be possible to log in to the server with the new version of bedrock?

No. Either old clients or new clients, but not both
