### ISSUE TITLE
Cannot parse argument '1.20(.1)' of option v/version

### ISSUE THREAD

**Issue by SkyEye-FAST** [ViaVersion/ViaProxy#70]
As in the title, "1.20" or "1.20.1" cannot be used for the -v or --version argument in the latest build (3.0.20-SNAPSHOT).

> [13:36:39] [main/INFO] (ViaProxy) Initializing ViaProxy CLI v3.0.20-SNAPSHOT (Injected using Launcher Agent)...
[13:36:39] [main/INFO] (ViaProxy) Using java version: OpenJDK 64-Bit Server VM 20 (Azul Systems, Inc.) on Linux
[13:36:39] [main/INFO] (ViaProxy) Available memory (bytes): 3139436544
Exception in thread "main" [13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]: joptsimple.OptionArgumentConversionException: Cannot parse argument '1.20.1' of option v/version
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:92)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:277)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at joptsimple.OptionSet.valuesOf(OptionSet.java:223)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at joptsimple.OptionSet.valueOf(OptionSet.java:172)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at net.raphimc.viaproxy.cli.options.Options.parse(Options.java:107)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at net.raphimc.viaproxy.ViaProxy.injectedMain(ViaProxy.java:144)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at net.raphimc.viaproxy.ViaProxy.main(ViaProxy.java:82)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]: Caused by: joptsimple.ValueConversionException: Unable to find version '1.20.1'
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at net.raphimc.viaproxy.cli.options.VersionEnumConverter.convert(VersionEnumConverter.java:31)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at net.raphimc.viaproxy.cli.options.VersionEnumConverter.convert(VersionEnumConverter.java:24)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at joptsimple.internal.Reflection.convertWith(Reflection.java:124)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:90)
[13:36:40] [main/INFO] (LoggerPrintStream) [STDERR]:    ... 6 more

**Comment by RaphiMC** [comment]
The version is called "1.20-1.20.1". But I agree the error should at least be more user friendly and suggest the correct version

**Comment by RaphiMC** [comment]
Changed the behaviour in the latest snapshot. It now accepts 1.20, 1.20.0 and 1.20.1 as valid inputs for 1.20-1.20.1
